<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>StudentSlideGenerator.Api</RootNamespace>
    <UserSecretsId>StudentSlideGenerator.Api-Local</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PdfPig" Version="0.1.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../StudentSlideGenerator.Shared/StudentSlideGenerator.Shared.csproj" />
  </ItemGroup>

</Project>
